[web]
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"

[file]
[backends]
  [backends.sitecore]
    [backends.sitecore.servers.server1]
    url = "http://web1:80"
    weight = 1
    [backends.sitecore.servers.server2]
    url = "http://web2:80"
    weight = 1

[frontends]
  [frontends.www]
  backend = "sitecore"
  entrypoints = ["http"] 
    [frontends.www.routes.all]
    rule = "Path:/"